import { Department, Employee } from "./types";

export const departments: Department[] = [
  {
    id: "dept-1",
    name: "Engineering",
    description: "Software development and infrastructure team",
    managerId: "emp-1",
    budget: 850000,
    location: "Floor 3 - Building A",
    createdAt: "2019-03-15",
    headcount: 18,
  },
  {
    id: "dept-2",
    name: "Human Resources",
    description: "People operations, recruiting and culture",
    managerId: "emp-4",
    budget: 320000,
    location: "Floor 1 - Building B",
    createdAt: "2018-01-10",
    headcount: 8,
  },
  {
    id: "dept-3",
    name: "Marketing",
    description: "Brand, growth and communications",
    managerId: "emp-7",
    budget: 420000,
    location: "Floor 2 - Building A",
    createdAt: "2019-06-01",
    headcount: 10,
  },
  {
    id: "dept-4",
    name: "Finance",
    description: "Accounting, budgeting and financial planning",
    managerId: "emp-10",
    budget: 290000,
    location: "Floor 1 - Building A",
    createdAt: "2018-04-20",
    headcount: 7,
  },
  {
    id: "dept-5",
    name: "Sales",
    description: "B2B sales, account management and business development",
    managerId: "emp-13",
    budget: 560000,
    location: "Floor 4 - Building B",
    createdAt: "2020-02-14",
    headcount: 14,
  },
  {
    id: "dept-6",
    name: "Operations",
    description: "Process optimization, logistics and support",
    managerId: "emp-16",
    budget: 380000,
    location: "Floor 2 - Building B",
    createdAt: "2019-11-05",
    headcount: 9,
  },
];

export const employees: Employee[] = [
  {
    id: "emp-1",
    firstName: "James",
    lastName: "Carter",
    email: "james.carter@datacor.com",
    phone: "+1 (555) 201-4400",
    position: "VP of Engineering",
    departmentId: "dept-1",
    status: "active",
    role: "admin",
    salary: 145000,
    startDate: "2019-03-15",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    address: "123 Oak St, San Francisco, CA 94102",
  },
  {
    id: "emp-2",
    firstName: "Sofia",
    lastName: "Hernandez",
    email: "sofia.hernandez@datacor.com",
    phone: "+1 (555) 201-4401",
    position: "Senior Software Engineer",
    departmentId: "dept-1",
    status: "active",
    role: "employee",
    salary: 118000,
    startDate: "2020-05-11",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia",
    address: "456 Pine Ave, Oakland, CA 94601",
  },
  {
    id: "emp-3",
    firstName: "Liam",
    lastName: "Nguyen",
    email: "liam.nguyen@datacor.com",
    phone: "+1 (555) 201-4402",
    position: "Frontend Developer",
    departmentId: "dept-1",
    status: "on-leave",
    role: "employee",
    salary: 95000,
    startDate: "2021-08-02",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Liam",
    address: "789 Elm Rd, Berkeley, CA 94710",
  },
  {
    id: "emp-4",
    firstName: "Rachel",
    lastName: "Kim",
    email: "rachel.kim@datacor.com",
    phone: "+1 (555) 201-4403",
    position: "HR Director",
    departmentId: "dept-2",
    status: "active",
    role: "manager",
    salary: 112000,
    startDate: "2018-01-10",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel",
    address: "321 Maple Dr, San Jose, CA 95101",
  },
  {
    id: "emp-5",
    firstName: "Daniel",
    lastName: "Brooks",
    email: "daniel.brooks@datacor.com",
    phone: "+1 (555) 201-4404",
    position: "HR Generalist",
    departmentId: "dept-2",
    status: "active",
    role: "employee",
    salary: 72000,
    startDate: "2021-03-22",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel",
    address: "654 Birch Ln, Fremont, CA 94538",
  },
  {
    id: "emp-6",
    firstName: "Mia",
    lastName: "Patel",
    email: "mia.patel@datacor.com",
    phone: "+1 (555) 201-4405",
    position: "Talent Acquisition Specialist",
    departmentId: "dept-2",
    status: "active",
    role: "employee",
    salary: 68000,
    startDate: "2022-01-17",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mia",
    address: "987 Cedar Ct, Palo Alto, CA 94301",
  },
  {
    id: "emp-7",
    firstName: "Ethan",
    lastName: "Walsh",
    email: "ethan.walsh@datacor.com",
    phone: "+1 (555) 201-4406",
    position: "Marketing Director",
    departmentId: "dept-3",
    status: "active",
    role: "manager",
    salary: 108000,
    startDate: "2019-06-01",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan",
    address: "147 Willow Way, Mountain View, CA 94041",
  },
  {
    id: "emp-8",
    firstName: "Ava",
    lastName: "Johnson",
    email: "ava.johnson@datacor.com",
    phone: "+1 (555) 201-4407",
    position: "Content Strategist",
    departmentId: "dept-3",
    status: "active",
    role: "employee",
    salary: 78000,
    startDate: "2020-09-14",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ava",
    address: "258 Aspen Pl, Sunnyvale, CA 94085",
  },
  {
    id: "emp-9",
    firstName: "Noah",
    lastName: "Davis",
    email: "noah.davis@datacor.com",
    phone: "+1 (555) 201-4408",
    position: "SEO Specialist",
    departmentId: "dept-3",
    status: "inactive",
    role: "employee",
    salary: 69000,
    startDate: "2021-11-30",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Noah",
    address: "369 Spruce St, Santa Clara, CA 95050",
  },
  {
    id: "emp-10",
    firstName: "Olivia",
    lastName: "Martinez",
    email: "olivia.martinez@datacor.com",
    phone: "+1 (555) 201-4409",
    position: "CFO",
    departmentId: "dept-4",
    status: "active",
    role: "admin",
    salary: 158000,
    startDate: "2018-04-20",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia",
    address: "741 Redwood Ave, Cupertino, CA 95014",
  },
  {
    id: "emp-11",
    firstName: "William",
    lastName: "Scott",
    email: "william.scott@datacor.com",
    phone: "+1 (555) 201-4410",
    position: "Senior Accountant",
    departmentId: "dept-4",
    status: "active",
    role: "employee",
    salary: 88000,
    startDate: "2019-08-05",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=William",
    address: "852 Magnolia Blvd, San Mateo, CA 94401",
  },
  {
    id: "emp-12",
    firstName: "Isabella",
    lastName: "Lee",
    email: "isabella.lee@datacor.com",
    phone: "+1 (555) 201-4411",
    position: "Financial Analyst",
    departmentId: "dept-4",
    status: "active",
    role: "employee",
    salary: 82000,
    startDate: "2022-03-07",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella",
    address: "963 Sequoia Dr, Redwood City, CA 94063",
  },
  {
    id: "emp-13",
    firstName: "Benjamin",
    lastName: "Clark",
    email: "benjamin.clark@datacor.com",
    phone: "+1 (555) 201-4412",
    position: "Sales Director",
    departmentId: "dept-5",
    status: "active",
    role: "manager",
    salary: 125000,
    startDate: "2020-02-14",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Benjamin",
    address: "159 Palm St, Menlo Park, CA 94025",
  },
  {
    id: "emp-14",
    firstName: "Charlotte",
    lastName: "Wilson",
    email: "charlotte.wilson@datacor.com",
    phone: "+1 (555) 201-4413",
    position: "Account Executive",
    departmentId: "dept-5",
    status: "active",
    role: "employee",
    salary: 84000,
    startDate: "2021-06-21",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Charlotte",
    address: "357 Walnut Ct, Foster City, CA 94404",
  },
  {
    id: "emp-15",
    firstName: "Henry",
    lastName: "Anderson",
    email: "henry.anderson@datacor.com",
    phone: "+1 (555) 201-4414",
    position: "Sales Development Rep",
    departmentId: "dept-5",
    status: "on-leave",
    role: "intern",
    salary: 48000,
    startDate: "2023-07-10",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Henry",
    address: "486 Cypress Ave, Burlingame, CA 94010",
  },
  {
    id: "emp-16",
    firstName: "Amelia",
    lastName: "Thomas",
    email: "amelia.thomas@datacor.com",
    phone: "+1 (555) 201-4415",
    position: "Operations Manager",
    departmentId: "dept-6",
    status: "active",
    role: "manager",
    salary: 98000,
    startDate: "2019-11-05",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amelia",
    address: "624 Poplar Ln, San Bruno, CA 94066",
  },
  {
    id: "emp-17",
    firstName: "Lucas",
    lastName: "White",
    email: "lucas.white@datacor.com",
    phone: "+1 (555) 201-4416",
    position: "Logistics Coordinator",
    departmentId: "dept-6",
    status: "active",
    role: "employee",
    salary: 64000,
    startDate: "2022-09-19",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    address: "735 Sycamore Dr, Daly City, CA 94014",
  },
  {
    id: "emp-18",
    firstName: "Grace",
    lastName: "Robinson",
    email: "grace.robinson@datacor.com",
    phone: "+1 (555) 201-4417",
    position: "Process Analyst",
    departmentId: "dept-6",
    status: "active",
    role: "employee",
    salary: 71000,
    startDate: "2023-02-01",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Grace",
    address: "846 Chestnut Blvd, Colma, CA 94014",
  },
];

export function getDepartmentById(id: string): Department | undefined {
  return departments.find((d) => d.id === id);
}

export function getEmployeeById(id: string): Employee | undefined {
  return employees.find((e) => e.id === id);
}

export function getEmployeesByDepartment(departmentId: string): Employee[] {
  return employees.filter((e) => e.departmentId === departmentId);
}

export function getDepartmentName(departmentId: string): string {
  return getDepartmentById(departmentId)?.name ?? "Unknown";
}
